//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using Service;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BoardMaker
	{
		public virtual FileReader FileReader
		{
			get;
			set;
		}

		public virtual string[][] loadBoard(object String mapChooser)
		{
			throw new System.NotImplementedException();
		}

		public virtual Board createBoard(object string[][] textBoard)
		{
			throw new System.NotImplementedException();
		}

	}
}

