//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GameController
	{
		public virtual Game Game
		{
			get;
			set;
		}

		public virtual void startGame(object Board gameBoard)
		{
			throw new System.NotImplementedException();
		}

		public virtual void movePlayer(object Directon direction)
		{
			throw new System.NotImplementedException();
		}

	}
}

