//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputController
	{
		public virtual GameController GameController
		{
			get;
			set;
		}

		public virtual ViewController ViewController
		{
			get;
			set;
		}

		public virtual BoardMaker BoardMaker
		{
			get;
			set;
		}

		public virtual void startSokoban()
		{
			throw new System.NotImplementedException();
		}

	}
}

