//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using View;

	public class ViewController
	{
		public virtual GameView GameView
		{
			get;
			set;
		}

		public virtual MenuView MenuView
		{
			get;
			set;
		}

		public virtual string showStartUpScreen()
		{
			throw new System.NotImplementedException();
		}

		public virtual string ShowGameScreen(object Board gameBoard)
		{
			throw new System.NotImplementedException();
		}

	}
}

