//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Board
	{
		public virtual IEnumerable<Floor> Floor
		{
			get;
			set;
		}

		public virtual Floor getFloor(object int xCoordinate, object int yCoordinate)
		{
			throw new System.NotImplementedException();
		}

		public virtual Floor[] getDestinations()
		{
			throw new System.NotImplementedException();
		}

	}
}

