//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Game
	{
		public virtual Board Board
		{
			get;
			set;
		}

		public virtual Player Player
		{
			get;
			set;
		}

		public virtual IEnumerable<Bomb> Bomb
		{
			get;
			set;
		}

		public virtual bool checkDestinations()
		{
			throw new System.NotImplementedException();
		}

		public virtual bool checkValidMove(object Direction direction)
		{
			throw new System.NotImplementedException();
		}

		public virtual void DoMove(object Direction direction)
		{
			throw new System.NotImplementedException();
		}

	}
}

