//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sokoban_DomainLib.GeneratedCode.Controller;

namespace Service
{
    using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Program
	{
		public InputController InputController
		{
			get;
			set;
		}

	}
}

